name: Testing self-hosted runners 

on:
  workflow_dispatch:

jobs:
  test:
    name: Build application
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm i
      - name: Build application
        run: npm run build