name: Testing self-hosted runners 

on:
  workflow_dispatch:

jobs:
  test:
    name: Deploy Application to GitHub pages
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ hashFiles('package.lock') }}
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Deploy Application
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/lunch-plans
